service:
  dm_api_account: 'http://5.63.153.31:5051'
  mailhog: 'http://5.63.153.31:5025'

user:
  login: 'kristinochka_26_11_2025_09_21_13_502'
  password: "123456789"

telegram:
  chat_id: '-1003486055147'
  token: 7718051598:AAGrdza5DzKYsZ_RO_qnRzkmszr9CyZPYMs